apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-demo-1
  namespace: {{ NS_NAME }}-ns
  labels:
    app: alb-demo-1
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alb-demo-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alb-demo-1
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: alb-demo-1
          configMap:
            name: alb-demo-1
      containers:
        - name: alb-demo-1
          image: {{ TEST_IMG }}
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 2
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: alb-demo-1
  namespace: {{ NS_NAME }}-ns
spec:
  selector:
    app: alb-demo-1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ MAIN_NODEPORT }}

    - name: health
      port: 8080
      targetPort: 8080
      nodePort: {{ HC_NODEPORT }}

