# permissions for end users to edit httpbackendgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpbackendgroup-editor-role
rules:
- apiGroups:
  - alb.yc.io
  resources:
  - httpbackendgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alb.yc.io
  resources:
  - httpbackendgroups/status
  verbs:
  - get
