apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-tls-testapp-deployment
  namespace: testapp-ns
  labels:
    app: grpc-tls-testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-testapp
  template:
    metadata:
      labels:
        app: grpc-testapp
    spec:
      initContainers:
        - name: generate-tls
          image: alpine/openssl:latest
          workingDir: "/etc/self_cert"
          command: ["/bin/sh","-c"]
          args: ["cd /etc/self_cert; openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout hc_key2.pem -out hc_cert.pem -batch; cat hc_key2.pem > hc_key.pem"]
          volumeMounts:
            - name: self-cert
              mountPath: "/etc/self_cert"
              readOnly: false
      containers:
        - name: srv
          image: grpc-testapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: PORT
              value: "8080"
            - name: SECURE_PORT
              value: "8443"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: self-cert
              mountPath: "/etc/self_cert"
              readOnly: true
      volumes:
        - name: self-cert
          emptyDir: {}
---

