apiVersion: v1
kind: ConfigMap
metadata:
  name: h2c-testapp
  namespace: testapp-ns
data:
  nginx.conf: |
    events {
    }
    
    http {
      server {
        listen 80 http2;
        listen [::]:80 http2;
        location / {
          add_header Content-Type text/plain;
          return 200 'This is H2C App';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2c-testapp-deployment
  namespace: testapp-ns
  labels:
    app: h2c-testapp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: h2c-testapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: h2c-testapp
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: h2c-testapp
          configMap:
            name: h2c-testapp
      containers:
        - name: h2c-testapp
          image: cr.yandex/mirror/nginx:latest
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: h2c-testapp
              mountPath: /etc/nginx
              readOnly: true
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
