apiVersion: v1
kind: Namespace
metadata:
  name: testapp-ns
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: testapp-ns
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: srv
        image: testapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SERVICE_NAME
          value: "testapp-1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment2
  namespace: testapp-ns
  labels:
    app: testapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
        - name: srv
          image: testapp:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: SERVICE_NAME
              value: "testapp-2"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Namespace
metadata:
  name: testapp2-ns
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: testapp2-ns
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: srv
          image: testapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_NAME
              value: "testapp-1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---