---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example1-ingress1
  namespace: {{ NS_NAME }}-ns
  annotations:
    ingress.alb.yc.io/group-name: default
    ingress.alb.yc.io/subnets: {{ SUBNET_A }},{{ SUBNET_B }},{{ SUBNET_C }}
    ingress.alb.yc.io/security-groups: {{ SG_1 }}
    ingress.alb.yc.io/external-ipv4-address: {{ ALB_IP }}
    ingress.alb.yc.io/request-timeout: 15s
    ingress.alb.yc.io/idle-timeout: 6m
    custom: anno1
spec:
  rules:
    - host: first-server.info
      http:
        paths:
          - path: /go
            pathType: Prefix
            backend:
              service:
                name: {{ APP_NAME_1 }}-service
                port:
                  number: {{ SVC_PORT }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example1-ingress2
  namespace: {{ NS_NAME }}-ns
  annotations:
    ingress.alb.yc.io/group-name: default
    ingress.alb.yc.io/security-groups: {{ SG_2 }}
    ingress.alb.yc.io/request-timeout: 15s
    ingress.alb.yc.io/idle-timeout: 6m
spec:
  rules:
    - host: first-server.info
      http:
        paths:
          - path: /vamoose
            pathType: Prefix
            backend:
              service:
                name: {{ APP_NAME_2 }}-service
                port:
                  number: {{ SVC_PORT }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example1-ingress3
  namespace: {{ NS_NAME }}-ns
  annotations:
    ingress.alb.yc.io/group-name: non-default
    ingress.alb.yc.io/subnets: {{ SUBNET_A }},{{ SUBNET_B }}
    ingress.alb.yc.io/external-ipv4-address: auto
    ingress.alb.yc.io/request-timeout: 15s
spec:
  tls:
    - hosts:
        - second-server.info
      secretName: yc-certmgr-cert-id-{{ CERTIFICATE_ID }}
  rules:
    - host: second-server.info
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: {{ APP_NAME_1 }}-service
                port:
                  number: {{ SVC_PORT }}
---
